import type { ThemeProperties } from '@/types/presentation';

export const themes: Record<string, ThemeProperties> = {
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean and professional',
    colors: {
      primary: '#18181B',
      secondary: '#71717A',
      background: '#FFFFFF',
      surface: '#F4F4F5',
      text: '#27272A',
      heading: '#09090B',
      muted: '#A1A1AA',
      accent: '#18181B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '8px',
    darkMode: false,
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Dark and modern',
    colors: {
      primary: '#60A5FA',
      secondary: '#93C5FD',
      background: '#0F172A',
      surface: '#1E293B',
      text: '#E2E8F0',
      heading: '#F8FAFC',
      muted: '#64748B',
      accent: '#60A5FA',
    },
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '12px',
    darkMode: true,
  },
  sunrise: {
    id: 'sunrise',
    name: 'Sunrise',
    description: 'Warm and inviting',
    colors: {
      primary: '#F97316',
      secondary: '#FB923C',
      background: '#FFF7ED',
      surface: '#FFEDD5',
      text: '#431407',
      heading: '#7C2D12',
      muted: '#9A3412',
      accent: '#F97316',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '12px',
    darkMode: false,
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    description: 'Natural and calm',
    colors: {
      primary: '#16A34A',
      secondary: '#22C55E',
      background: '#F0FDF4',
      surface: '#DCFCE7',
      text: '#14532D',
      heading: '#052E16',
      muted: '#166534',
      accent: '#16A34A',
    },
    fonts: { heading: 'Playfair Display', body: 'DM Sans' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '8px',
    darkMode: false,
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    description: 'Cool and professional',
    colors: {
      primary: '#2563EB',
      secondary: '#3B82F6',
      background: '#EFF6FF',
      surface: '#DBEAFE',
      text: '#1E3A5F',
      heading: '#1E3A8A',
      muted: '#3B82F6',
      accent: '#2563EB',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '8px',
    darkMode: false,
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender',
    description: 'Soft and creative',
    colors: {
      primary: '#7C3AED',
      secondary: '#8B5CF6',
      background: '#F5F3FF',
      surface: '#EDE9FE',
      text: '#3B0764',
      heading: '#4C1D95',
      muted: '#6D28D9',
      accent: '#7C3AED',
    },
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '12px',
    darkMode: false,
  },
  coral: {
    id: 'coral',
    name: 'Coral',
    description: 'Vibrant and energetic',
    colors: {
      primary: '#F43F5E',
      secondary: '#FB7185',
      background: '#FFF1F2',
      surface: '#FFE4E6',
      text: '#4C0519',
      heading: '#881337',
      muted: '#BE123C',
      accent: '#F43F5E',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '16px',
    darkMode: false,
  },
  slate: {
    id: 'slate',
    name: 'Slate',
    description: 'Professional and neutral',
    colors: {
      primary: '#475569',
      secondary: '#64748B',
      background: '#F8FAFC',
      surface: '#F1F5F9',
      text: '#334155',
      heading: '#0F172A',
      muted: '#94A3B8',
      accent: '#475569',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '6px',
    darkMode: false,
  },
  carbon: {
    id: 'carbon',
    name: 'Carbon',
    description: 'Dark and minimal',
    colors: {
      primary: '#FAFAFA',
      secondary: '#A1A1AA',
      background: '#18181B',
      surface: '#27272A',
      text: '#D4D4D8',
      heading: '#FAFAFA',
      muted: '#71717A',
      accent: '#FAFAFA',
    },
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '8px',
    darkMode: true,
  },
  vintage: {
    id: 'vintage',
    name: 'Vintage',
    description: 'Warm and classic',
    colors: {
      primary: '#92400E',
      secondary: '#B45309',
      background: '#FFFBEB',
      surface: '#FEF3C7',
      text: '#451A03',
      heading: '#78350F',
      muted: '#92400E',
      accent: '#D97706',
    },
    fonts: { heading: 'Playfair Display', body: 'DM Sans' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '4px',
    darkMode: false,
  },
  neon: {
    id: 'neon',
    name: 'Neon',
    description: 'Bold and cyber',
    colors: {
      primary: '#22D3EE',
      secondary: '#A78BFA',
      background: '#020617',
      surface: '#0F172A',
      text: '#CBD5E1',
      heading: '#F0F9FF',
      muted: '#475569',
      accent: '#22D3EE',
    },
    fonts: { heading: 'Space Grotesk', body: 'Space Grotesk' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '8px',
    darkMode: true,
  },
  paper: {
    id: 'paper',
    name: 'Paper',
    description: 'Warm and readable',
    colors: {
      primary: '#854D0E',
      secondary: '#A16207',
      background: '#FEFCE8',
      surface: '#FEF9C3',
      text: '#422006',
      heading: '#713F12',
      muted: '#A16207',
      accent: '#CA8A04',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    spacing: { padding: 48, gap: 24 },
    borderRadius: '4px',
    darkMode: false,
  },
};

export const themeList = Object.values(themes);
export const getTheme = (id: string): ThemeProperties => themes[id] || themes.minimal;
